"use client";
import { useState, useEffect } from "react";
import DashboardLayout from "../../components/shared/DashboardLayout.js";
import ChatWidget from "../../components/ai/ChatWidget.js";
import { get, post } from "../../lib/api.js";
import { getUser } from "../../lib/auth.js";

function downloadPayslipPdf(slip) {
  // Dynamic import to avoid SSR issues
  import("jspdf").then(({ jsPDF }) => {
    const doc = new jsPDF();
    const month = new Date(0, slip.month - 1).toLocaleString("default", { month: "long" });

    doc.setFontSize(20);
    doc.setTextColor(37, 99, 235);
    doc.text("HRMS — Payslip", 20, 25);

    doc.setFontSize(11);
    doc.setTextColor(100, 100, 100);
    doc.text(`Period: ${month} ${slip.year}`, 20, 38);
    doc.text(`Employee: ${slip.employee?.name || "—"} (${slip.employee?.employeeId || "—"})`, 20, 46);
    doc.text(`Department: ${slip.employee?.department || "—"}`, 20, 54);
    doc.text(`Designation: ${slip.employee?.designation || "—"}`, 20, 62);

    doc.setDrawColor(220, 220, 220);
    doc.line(20, 68, 190, 68);

    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    const items = [
      ["Basic Salary", `₹${slip.basicSalary?.toLocaleString()}`],
      ["Allowances", `+ ₹${slip.allowances?.toLocaleString()}`],
      ["Deductions", `- ₹${slip.deductions?.toLocaleString()}`],
    ];
    items.forEach(([label, value], i) => {
      doc.text(label, 20, 80 + i * 10);
      doc.text(value, 150, 80 + i * 10);
    });

    doc.line(20, 112, 190, 112);
    doc.setFontSize(14);
    doc.setTextColor(37, 99, 235);
    doc.text("Net Salary", 20, 122);
    doc.text(`₹${slip.netSalary?.toLocaleString()}`, 150, 122);

    doc.setFontSize(9);
    doc.setTextColor(160, 160, 160);
    doc.text("Generated by HRMS — FWC Hackathon", 20, 280);

    doc.save(`payslip-${month}-${slip.year}.pdf`);
  });
}

export default function PayrollPage() {
  const user = getUser();
  const [slips, setSlips] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [genForm, setGenForm] = useState({ month: new Date().getMonth() + 1, year: new Date().getFullYear() });

  useEffect(() => {
    async function load() {
      if (!user?.employeeId) return setLoading(false);
      try {
        const data = await get(`/api/payroll/${user.employeeId}/slips`);
        setSlips(data || []);
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, []);

  async function generatePayroll() {
    setGenerating(true);
    try {
      await post("/api/payroll/generate", genForm);
      alert("✅ Payroll generated for all active employees!");
    } catch (e) {
      alert(e.message);
    } finally {
      setGenerating(false);
    }
  }

  const latest = slips[0];
  const isHR = user?.role === "admin" || user?.role === "hr_recruiter";

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">Payroll</h2>
          <p className="text-gray-500 text-sm mt-1">Salary breakdown and payslips</p>
        </div>

        {/* Latest salary card */}
        {latest && (
          <div className="card bg-gradient-to-r from-blue-600 to-indigo-600 text-white">
            <p className="text-blue-200 text-sm">Latest Payslip — {new Date(0, latest.month - 1).toLocaleString("default", { month: "long" })} {latest.year}</p>
            <p className="text-4xl font-bold mt-2">₹{latest.netSalary?.toLocaleString()}</p>
            <div className="flex gap-6 mt-4 text-sm text-blue-100">
              <div><p className="text-blue-300">Basic</p><p className="font-semibold text-white">₹{latest.basicSalary?.toLocaleString()}</p></div>
              <div><p className="text-blue-300">Allowances</p><p className="font-semibold text-white">+₹{latest.allowances?.toLocaleString()}</p></div>
              <div><p className="text-blue-300">Deductions</p><p className="font-semibold text-white">-₹{latest.deductions?.toLocaleString()}</p></div>
            </div>
            <button
              onClick={() => downloadPayslipPdf({ ...latest, employee: { name: user.name, employeeId: user.employeeId } })}
              className="mt-4 bg-white/20 hover:bg-white/30 text-white text-sm font-medium px-4 py-2 rounded-lg transition-colors"
            >
              ⬇️ Download PDF
            </button>
          </div>
        )}

        {/* HR: Generate Payroll */}
        {isHR && (
          <div className="card">
            <h3 className="font-semibold text-gray-900 mb-4">Generate Payroll</h3>
            <div className="flex flex-wrap gap-3 items-end">
              <div>
                <label className="text-sm text-gray-600 block mb-1">Month</label>
                <select className="input w-40" value={genForm.month} onChange={e => setGenForm(f => ({ ...f, month: Number(e.target.value) }))}>
                  {Array.from({ length: 12 }, (_, i) => i + 1).map(m => (
                    <option key={m} value={m}>{new Date(0, m - 1).toLocaleString("default", { month: "long" })}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="text-sm text-gray-600 block mb-1">Year</label>
                <input type="number" className="input w-28" value={genForm.year}
                  onChange={e => setGenForm(f => ({ ...f, year: Number(e.target.value) }))} />
              </div>
              <button onClick={generatePayroll} disabled={generating} className="btn-primary">
                {generating ? "Generating..." : "💰 Generate for All Employees"}
              </button>
            </div>
          </div>
        )}

        {/* Slips table */}
        <div className="card overflow-x-auto">
          <h3 className="font-semibold text-gray-900 mb-4">Payslip History</h3>
          {loading ? (
            <div className="text-center py-8 text-gray-400">Loading...</div>
          ) : (
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100">
                  {["Period", "Basic", "Allowances", "Deductions", "Net Salary", "Status", ""].map(h => (
                    <th key={h} className="text-left py-2 px-3 text-gray-500 font-medium">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {slips.map(slip => (
                  <tr key={slip._id} className="border-b border-gray-50 hover:bg-gray-50">
                    <td className="py-3 px-3 font-medium text-gray-900">
                      {new Date(0, slip.month - 1).toLocaleString("default", { month: "short" })} {slip.year}
                    </td>
                    <td className="py-3 px-3 text-gray-600">₹{slip.basicSalary?.toLocaleString()}</td>
                    <td className="py-3 px-3 text-green-600">+₹{slip.allowances?.toLocaleString()}</td>
                    <td className="py-3 px-3 text-red-500">-₹{slip.deductions?.toLocaleString()}</td>
                    <td className="py-3 px-3 font-semibold text-gray-900">₹{slip.netSalary?.toLocaleString()}</td>
                    <td className="py-3 px-3">
                      <span className={`badge capitalize ${slip.status === "paid" ? "bg-green-100 text-green-700" : slip.status === "processed" ? "bg-blue-100 text-blue-700" : "bg-yellow-100 text-yellow-700"}`}>
                        {slip.status}
                      </span>
                    </td>
                    <td className="py-3 px-3">
                      <button
                        onClick={() => downloadPayslipPdf({ ...slip, employee: slip.employee || { name: user.name, employeeId: user.employeeId } })}
                        className="text-xs text-blue-600 hover:underline"
                      >
                        ⬇️ PDF
                      </button>
                    </td>
                  </tr>
                ))}
                {slips.length === 0 && (
                  <tr><td colSpan={7} className="text-center py-8 text-gray-400">No payslips found</td></tr>
                )}
              </tbody>
            </table>
          )}
        </div>
      </div>
      <ChatWidget />
    </DashboardLayout>
  );
}
